version: "3.8"

services:
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:80"
    volumes:
      - ./packages/frontend/public:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - task

  backend:
    build: ./packages/backend
    ports:
      - "4000:4000"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    depends_on:
      - database
    command: npm start
    networks:
      - task

  database:
    build: ./packages/database
    ports:
      - "5432:5432"
    volumes:
      - ./packages/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - task

networks:
  task:
