version: "3.8"

services:
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:80"
    volumes:
      - ./packages/frontend/public:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./packages/backend
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/app
    depends_on:
      - database
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase

  database:
    build: ./packages/database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

volumes:
  db_data:
